var dir_49da38e81ad9b9721ecaeecc19561512 =
[
    [ "avr", "dir_7a28e0b9a0383944905aeaff72448b0b.html", "dir_7a28e0b9a0383944905aeaff72448b0b" ],
    [ "avr_adc.h", "avr__adc_8h.html", "avr__adc_8h" ],
    [ "avr_bitbang.h", "avr__bitbang_8h.html", "avr__bitbang_8h" ],
    [ "avr_eeprom.h", "avr__eeprom_8h.html", "avr__eeprom_8h" ],
    [ "avr_extint.h", "avr__extint_8h.html", "avr__extint_8h" ],
    [ "avr_flash.h", "avr__flash_8h.html", "avr__flash_8h" ],
    [ "avr_ioport.h", "avr__ioport_8h.html", "avr__ioport_8h" ],
    [ "avr_lin.h", "avr__lin_8h.html", "avr__lin_8h" ],
    [ "avr_spi.h", "avr__spi_8h.html", "avr__spi_8h" ],
    [ "avr_timer.h", "avr__timer_8h.html", "avr__timer_8h" ],
    [ "avr_twi.h", "avr__twi_8h.html", "avr__twi_8h" ],
    [ "avr_uart.h", "avr__uart_8h.html", "avr__uart_8h" ],
    [ "avr_usb.h", "avr__usb_8h.html", "avr__usb_8h" ],
    [ "avr_watchdog.h", "avr__watchdog_8h.html", "avr__watchdog_8h" ],
    [ "doc.h", "doc_8h.html", null ],
    [ "fifo_declare.h", "fifo__declare_8h.html", "fifo__declare_8h" ],
    [ "logging.h", "logging_8h.html", "logging_8h" ],
    [ "sim_avr.h", "sim__avr_8h.html", "sim__avr_8h" ],
    [ "sim_avr_types.h", "sim__avr__types_8h.html", "sim__avr__types_8h" ],
    [ "sim_core.h", "sim__core_8h.html", "sim__core_8h" ],
    [ "sim_cycle_timers.h", "sim__cycle__timers_8h.html", "sim__cycle__timers_8h" ],
    [ "sim_elf.h", "sim__elf_8h.html", "sim__elf_8h" ],
    [ "sim_gdb.h", "sim__gdb_8h.html", "sim__gdb_8h" ],
    [ "sim_hex.h", "sim__hex_8h.html", "sim__hex_8h" ],
    [ "sim_interrupts.h", "sim__interrupts_8h.html", "sim__interrupts_8h" ],
    [ "sim_io.h", "sim__io_8h.html", "sim__io_8h" ],
    [ "sim_irq.h", "sim__irq_8h.html", "sim__irq_8h" ],
    [ "sim_network.h", "sim__network_8h.html", "sim__network_8h" ],
    [ "sim_regbit.h", "sim__regbit_8h.html", "sim__regbit_8h" ],
    [ "sim_time.h", "sim__time_8h.html", "sim__time_8h" ],
    [ "sim_vcd_file.h", "sim__vcd__file_8h.html", "sim__vcd__file_8h" ]
];