var modules =
[
    [ "ADC", "group__avr__adc.html", "group__avr__adc" ],
    [ "Generic BitBang Module", "group__avr__bitbang.html", "group__avr__bitbang" ],
    [ "EEPROM", "group__avr__eeprom.html", "group__avr__eeprom" ],
    [ "Extern Interrupt", "group__avr__extint.html", "group__avr__extint" ],
    [ "Flash", "group__avr__flash.html", "group__avr__flash" ],
    [ "IO Port", "group__avr__ioport.html", "group__avr__ioport" ],
    [ "LIN", "group__avr__lin.html", "group__avr__lin" ],
    [ "SPI", "group__avr__spi.html", "group__avr__spi" ],
    [ "Timer", "group__avr__timer.html", "group__avr__timer" ],
    [ "TWI", "group__avr__twi.html", "group__avr__twi" ],
    [ "UART", "group__avr__uart.html", "group__avr__uart" ],
    [ "USB", "group__avr__usb.html", "group__avr__usb" ],
    [ "Watchdog", "group__avr__watchdog.html", "group__avr__watchdog" ],
    [ "FIFO helpers, aka circular buffers", "group__fifo__declare.html", "group__fifo__declare" ],
    [ "Logging", "group__logging.html", "group__logging" ],
    [ "AVR Simulation", "group__sim__avr.html", "group__sim__avr" ],
    [ "AVR Types", "group__sim__avr__types.html", "group__sim__avr__types" ],
    [ "Core Simulation", "group__sim__core.html", "group__sim__core" ],
    [ "Cycle Timers", "group__sim__cycle__timers.html", "group__sim__cycle__timers" ],
    [ "ELF Support", "group__sim__elf.html", "group__sim__elf" ],
    [ "GDB", "group__sim__gdb.html", "group__sim__gdb" ],
    [ "Hex Firmware", "group__sim__hex.html", "group__sim__hex" ],
    [ "Interrupts", "group__sim__interrupts.html", "group__sim__interrupts" ],
    [ "IO", "group__sim__io.html", "group__sim__io" ],
    [ "Internal IRQ System (simulator callback)", "group__sim__irq.html", "group__sim__irq" ],
    [ "Network", "group__sim__network.html", "group__sim__network" ],
    [ "Register Bit", "group__sim__regbit.html", "group__sim__regbit" ],
    [ "Time Functions", "group__sim__time.html", "group__sim__time" ],
    [ "Value Change Dump", "group__sim__vcd__file.html", "group__sim__vcd__file" ]
];